<a href="https://colab.research.google.com/github/hs992090-rgb/Student-Performance-Prediction/blob/main/Final_Project_Student_Performance_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# from google.colab import files
# uploaded = files.upload()

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('student_performance.csv')

In [ ]:
df

,Name,Age,Gender,Major,Living_Area,Parent_Education,Scholarship_Status,Part_Time_Job,Extracurricular_Activities,Internet_Access,...,Sleep_Hours_Per_Day,Attendance_Rate,Stress_Level,Exam_Proximity,Math_Score,Science_Score,Language_Score,History_Score,Average_Score,Grade
0,Linda Johnson,24,Female,Arts,Rural,Bachelor,No,No,No,Yes,...,6.69,77.3,3.6,No,52,43,69,66,58,C
1,Thomas Thomas,21,Male,Arts,Suburban,Master,No,No,No,Yes,...,7.34,59.7,7.3,Yes,59,64,74,68,66,C
2,Joseph Rodriguez,23,Male,STEM,Suburban,High School,Yes,No,No,Yes,...,6.78,56.0,2.9,No,81,72,67,69,72,B
3,Michael Wright,25,Male,STEM,Rural,High School,No,No,No,Yes,...,9.59,84.9,3.2,No,63,72,55,58,62,C
4,Jennifer Nguyen,25,Female,Arts,Urban,Bachelor,Yes,No,No,Yes,...,7.04,98.2,4.6,Yes,69,76,90,86,80,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Elizabeth Hernandez,18,Female,Arts,Urban,PhD,No,No,No,Yes,...,8.08,84.1,3.9,Yes,76,75,97,91,85,A
996,Joshua Hill,20,Male,Business,Rural,PhD,No,No,No,Yes,...,6.92,74.4,3.6,No,92,79,82,71,81,B
997,Nancy Torres,22,Female,Humanities,Rural,Bachelor,No,Yes,No,Yes,...,6.82,72.8,5.2,No,70,60,73,71,69,C
998,Robert Johnson,19,Male,Humanities,Urban,High School,No,No,No,Yes,...,7.58,83.2,5.7,Yes,53,56,54,56,55,C
999,Jennifer Williams,25,Female,Arts,Suburban,High School,No,No,Yes,Yes,...,8.83,67.9,4.3,Yes,57,67,70,61,64,C

##  DATA CLEANING

In [ ]:

df.isnull().sum()

Name                          0
Age                           0
Gender                        0
Major                         0
Living_Area                   0
Parent_Education              0
Scholarship_Status            0
Part_Time_Job                 0
Extracurricular_Activities    0
Internet_Access               0
Study_Hours_Per_Day           0
Sleep_Hours_Per_Day           0
Attendance_Rate               0
Stress_Level                  0
Exam_Proximity                0
Math_Score                    0
Science_Score                 0
Language_Score                0
History_Score                 0
Average_Score                 0
Grade                         0
dtype: int64

In [ ]:
(df==0).sum()

Name                          0
Age                           0
Gender                        0
Major                         0
Living_Area                   0
Parent_Education              0
Scholarship_Status            0
Part_Time_Job                 0
Extracurricular_Activities    0
Internet_Access               0
Study_Hours_Per_Day           0
Sleep_Hours_Per_Day           0
Attendance_Rate               0
Stress_Level                  0
Exam_Proximity                0
Math_Score                    0
Science_Score                 0
Language_Score                0
History_Score                 0
Average_Score                 0
Grade                         0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(1000, 21)

In [ ]:
df=df.drop(columns=['Name','Age','Gender'])

In [ ]:
df.shape

(1000, 18)

In [ ]:
for col in df.columns:
  if df[col].dtype == 'object':
    print(f" {col} -> {df[col].unique()}")

 Major -> ['Arts' 'STEM' 'Business' 'Humanities']
 Living_Area -> ['Rural' 'Suburban' 'Urban']
 Parent_Education -> ['Bachelor' 'Master' 'High School' 'PhD']
 Scholarship_Status -> ['No' 'Yes']
 Part_Time_Job -> ['No' 'Yes']
 Extracurricular_Activities -> ['No' 'Yes']
 Internet_Access -> ['Yes' 'No']
 Exam_Proximity -> ['No' 'Yes']
 Grade -> ['C' 'B' 'A' 'F' 'D']

In [ ]:
# nominal encoding (one hot encoding) - >  Scholarship_Status ,  Part_Time_Job  , Extracurricular_Activities  ,  Internet_Access , Exam_Proximity

# ordinal encoding -> Living_area , Parent_Education , Grade

# Label Encoing -> Major

In [ ]:
# nominal encoding
df=pd.get_dummies(df,columns=['Scholarship_Status','Part_Time_Job','Extracurricular_Activities','Internet_Access','Exam_Proximity'],drop_first=True)

In [ ]:
df

,Major,Living_Area,Parent_Education,Study_Hours_Per_Day,Sleep_Hours_Per_Day,Attendance_Rate,Stress_Level,Math_Score,Science_Score,Language_Score,History_Score,Average_Score,Grade,Scholarship_Status_Yes,Part_Time_Job_Yes,Extracurricular_Activities_Yes,Internet_Access_Yes,Exam_Proximity_Yes
0,Arts,Rural,Bachelor,1.24,6.69,77.3,3.6,52,43,69,66,58,C,False,False,False,True,False
1,Arts,Suburban,Master,3.67,7.34,59.7,7.3,59,64,74,68,66,C,False,False,False,True,True
2,STEM,Suburban,High School,5.31,6.78,56.0,2.9,81,72,67,69,72,B,True,False,False,True,False
3,STEM,Rural,High School,2.70,9.59,84.9,3.2,63,72,55,58,62,C,False,False,False,True,False
4,Arts,Urban,Bachelor,3.59,7.04,98.2,4.6,69,76,90,86,80,B,True,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Arts,Urban,PhD,8.86,8.08,84.1,3.9,76,75,97,91,85,A,False,False,False,True,True
996,Business,Rural,PhD,4.42,6.92,74.4,3.6,92,79,82,71,81,B,False,False,False,True,False
997,Humanities,Rural,Bachelor,2.51,6.82,72.8,5.2,70,60,73,71,69,C,False,True,False,True,False
998,Humanities,Urban,High School,1.26,7.58,83.2,5.7,53,56,54,56,55,C,False,False,False,True,True
999,Arts,Suburban,High School,2.13,8.83,67.9,4.3,57,67,70,61,64,C,False,False,True,True,True

In [ ]:
# ordinal encoding
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=[['Rural','Suburban','Urban'],['High School','Bachelor','Master','PhD'],['A','B','C','D','F']])
df[['Living_Area','Parent_Education','Grade']] = oe.fit_transform(df[['Living_Area','Parent_Education','Grade']])

In [ ]:
df['Grade'].unique()

array([2., 1., 0., 4., 3.])

In [ ]:
df

,Major,Living_Area,Parent_Education,Study_Hours_Per_Day,Sleep_Hours_Per_Day,Attendance_Rate,Stress_Level,Math_Score,Science_Score,Language_Score,History_Score,Average_Score,Grade,Scholarship_Status_Yes,Part_Time_Job_Yes,Extracurricular_Activities_Yes,Internet_Access_Yes,Exam_Proximity_Yes
0,Arts,0.0,1.0,1.24,6.69,77.3,3.6,52,43,69,66,58,2.0,False,False,False,True,False
1,Arts,1.0,2.0,3.67,7.34,59.7,7.3,59,64,74,68,66,2.0,False,False,False,True,True
2,STEM,1.0,0.0,5.31,6.78,56.0,2.9,81,72,67,69,72,1.0,True,False,False,True,False
3,STEM,0.0,0.0,2.70,9.59,84.9,3.2,63,72,55,58,62,2.0,False,False,False,True,False
4,Arts,2.0,1.0,3.59,7.04,98.2,4.6,69,76,90,86,80,1.0,True,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Arts,2.0,3.0,8.86,8.08,84.1,3.9,76,75,97,91,85,0.0,False,False,False,True,True
996,Business,0.0,3.0,4.42,6.92,74.4,3.6,92,79,82,71,81,1.0,False,False,False,True,False
997,Humanities,0.0,1.0,2.51,6.82,72.8,5.2,70,60,73,71,69,2.0,False,True,False,True,False
998,Humanities,2.0,0.0,1.26,7.58,83.2,5.7,53,56,54,56,55,2.0,False,False,False,True,True
999,Arts,1.0,0.0,2.13,8.83,67.9,4.3,57,67,70,61,64,2.0,False,False,True,True,True

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le  =LabelEncoder()

In [ ]:
df['Major']=le.fit_transform(df['Major'])

In [ ]:
df

,Major,Living_Area,Parent_Education,Study_Hours_Per_Day,Sleep_Hours_Per_Day,Attendance_Rate,Stress_Level,Math_Score,Science_Score,Language_Score,History_Score,Average_Score,Grade,Scholarship_Status_Yes,Part_Time_Job_Yes,Extracurricular_Activities_Yes,Internet_Access_Yes,Exam_Proximity_Yes
0,0,0.0,1.0,1.24,6.69,77.3,3.6,52,43,69,66,58,2.0,False,False,False,True,False
1,0,1.0,2.0,3.67,7.34,59.7,7.3,59,64,74,68,66,2.0,False,False,False,True,True
2,3,1.0,0.0,5.31,6.78,56.0,2.9,81,72,67,69,72,1.0,True,False,False,True,False
3,3,0.0,0.0,2.70,9.59,84.9,3.2,63,72,55,58,62,2.0,False,False,False,True,False
4,0,2.0,1.0,3.59,7.04,98.2,4.6,69,76,90,86,80,1.0,True,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,2.0,3.0,8.86,8.08,84.1,3.9,76,75,97,91,85,0.0,False,False,False,True,True
996,1,0.0,3.0,4.42,6.92,74.4,3.6,92,79,82,71,81,1.0,False,False,False,True,False
997,2,0.0,1.0,2.51,6.82,72.8,5.2,70,60,73,71,69,2.0,False,True,False,True,False
998,2,2.0,0.0,1.26,7.58,83.2,5.7,53,56,54,56,55,2.0,False,False,False,True,True
999,0,1.0,0.0,2.13,8.83,67.9,4.3,57,67,70,61,64,2.0,False,False,True,True,True

## I/p - o/p

In [ ]:
X = df.drop(columns=['Grade'])

In [ ]:
X.shape

(1000, 17)

In [ ]:
y=df['Grade']

In [ ]:
y.shape

(1000,)

In [ ]:
df.describe()

,Major,Living_Area,Parent_Education,Study_Hours_Per_Day,Sleep_Hours_Per_Day,Attendance_Rate,Stress_Level,Math_Score,Science_Score,Language_Score,History_Score,Average_Score,Grade
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.0000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,1.674000,1.206000,0.901000,4.286350,7.048220,78.418000,4.060500,70.8390,69.789000,72.719000,69.482000,70.831000,1.430000
std,1.152846,0.743045,0.849659,2.621616,1.242238,13.599243,1.648164,12.8598,12.231929,12.485188,12.345934,10.256004,0.741384
min,0.000000,0.000000,0.000000,0.500000,2.500000,40.000000,1.000000,25.0000,28.000000,29.000000,26.000000,37.000000,0.000000
25%,1.000000,1.000000,0.000000,2.387500,6.210000,69.275000,2.800000,62.0000,62.000000,64.000000,61.000000,64.000000,1.000000
50%,2.000000,1.000000,1.000000,3.805000,7.080000,80.950000,3.900000,71.0000,70.000000,73.000000,69.000000,71.000000,1.000000
75%,3.000000,2.000000,1.000000,5.815000,7.900000,89.100000,5.300000,80.0000,78.000000,81.000000,77.000000,78.000000,2.000000
max,3.000000,2.000000,3.000000,15.500000,11.000000,99.800000,9.400000,100.0000,100.000000,100.000000,100.000000,97.000000,4.000000

In [ ]:
## splittting
from imblearn.over_sampling import SMOTE

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
## Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

# Apply SMOTE to the training data with n_neighbors=1 to handle small classes
sm = SMOTE(random_state=42, k_neighbors=1)
X_train_res, y_train_res = sm.fit_resample(X_train_scaled, y_train)

print(f"Shape of X_train after SMOTE: {X_train_res.shape}")
print(f"Shape of y_train after SMOTE: {y_train_res.shape}")

Shape of X_train after SMOTE: (1885, 17)
Shape of y_train after SMOTE: (1885,)

## Tensorflow , keras ( Neural Network Building)

In [ ]:
import tensorflow as tf
from tensorflow import keras

from tensorflow.keras import Sequential
from tensorflow.keras import Input
from tensorflow.keras.layers import Dense

In [ ]:
model = Sequential()

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
X.shape

(1000, 17)

In [ ]:
# Input Layer

model.add(Input(shape=(17,)))

# Hidden Layer - 1

model.add(Dense(1024,activation = 'relu'))

# Hidden Layer - 2

model.add(Dense(512,activation = 'relu'))

# Hidden Layer - 3

model.add(Dense(256,activation = 'relu'))

# output layer

model.add(Dense(5,activation = 'softmax'))

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1024)           │        18,432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 512)            │       524,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 5)              │         1,285 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 675,845 (2.58 MB)

 Trainable params: 675,845 (2.58 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(loss='sparse_categorical_crossentropy',metrics=['accuracy'] )

In [ ]:
## Early Stopping

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
early_stop = EarlyStopping(monitor = 'val_loss',patience=10,restore_best_weights=True,mode='min')

In [ ]:
## model fitting

In [ ]:
model.fit(X_train_res, y_train_res, epochs=20, validation_data=(X_test_scaled, y_test), callbacks=[early_stop])

Epoch 1/20
59/59 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.8175 - loss: 0.4492 - val_accuracy: 0.7950 - val_loss: 0.5183
Epoch 2/20
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.9538 - loss: 0.1389 - val_accuracy: 0.8500 - val_loss: 0.4461
Epoch 3/20
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.9533 - loss: 0.1199 - val_accuracy: 0.8950 - val_loss: 0.3004
Epoch 4/20
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.9586 - loss: 0.1135 - val_accuracy: 0.8800 - val_loss: 0.3241
Epoch 5/20
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.9698 - loss: 0.0784 - val_accuracy: 0.8750 - val_loss: 0.5047
Epoch 6/20
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9804 - loss: 0.0465 - val_accuracy: 0.8400 - val_loss: 0.6007
Epoch 7/20
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.9756 - loss: 0.0733 - val_accuracy: 0.8850 - val_loss: 0.3977
Epoch 8/20
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9825 - loss: 0.0405 - val_accuracy: 0.8750 - val_loss: 0.5427
Epoch 9/20
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.9841 - loss: 0.0439 - val_accuracy: 0.8900 - val_loss: 0.4372
Epoch 10/20
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.9878 - loss: 0.0394 - val_accuracy: 0.8250 - val_loss: 0.9617
Epoch 11/20
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.9931 - loss: 0.0170 - val_accuracy: 0.8800 - val_loss: 0.5700
Epoch 12/20
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.9905 - loss: 0.0400 - val_accuracy: 0.8250 - val_loss: 0.9401
Epoch 13/20
59/59 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.9905 - loss: 0.0329 - val_accuracy: 0.8950 - val_loss: 0.3975

In [ ]:
y_pred = model.predict(X_test_scaled)
y_pred

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

array([[2.07767043e-05, 1.41312520e-03, 9.65171039e-01, 3.28895971e-02,
        5.05404838e-04],
       [1.50600829e-06, 5.92974597e-04, 9.96591449e-01, 2.78940308e-03,
        2.45455285e-05],
       [2.32408908e-07, 5.02732437e-05, 9.55426216e-01, 4.44848873e-02,
        3.84074556e-05],
       [1.87912560e-03, 9.97989476e-01, 1.31031935e-04, 7.54715828e-08,
        2.35335406e-07],
       [1.09456214e-05, 1.81434338e-03, 9.75704789e-01, 2.24281084e-02,
        4.17988558e-05],
       [2.11839595e-08, 3.24147418e-02, 9.67583299e-01, 1.82995643e-06,
        1.59013391e-09],
       [1.13227671e-07, 8.53555184e-03, 9.91444886e-01, 1.95071843e-05,
        4.41601422e-08],
       [7.36294760e-06, 9.94699895e-01, 5.29257860e-03, 1.35849746e-07,
        1.80145712e-08],
       [4.55429671e-07, 6.14262521e-02, 9.38558280e-01, 1.48168319e-05,
        7.78205163e-08],
       [2.11344188e-04, 9.90111232e-01, 9.67182685e-03, 4.75398383e-06,
        8.69284236e-07],
       [2.89797962e-01, 7.10201800e-01, 2.63726918e-07, 4.57197252e-10,
        1.07675966e-08],
       [2.80956847e-05, 2.16702744e-01, 7.83156395e-01, 1.11297493e-04,
        1.52175687e-06],
       [9.99633372e-01, 3.66724533e-04, 1.14087940e-11, 1.73440662e-13,
        3.57110973e-11],
       [2.83021997e-08, 6.20146806e-04, 9.99305010e-01, 7.48894599e-05,
        5.15906535e-08],
       [1.07379196e-06, 4.79808636e-03, 9.94545519e-01, 6.53913012e-04,
        1.25734425e-06],
       [2.12888807e-01, 7.87095845e-01, 1.43108991e-05, 6.11994579e-08,
        8.78977744e-07],
       [1.05488762e-05, 1.15188304e-02, 9.87462699e-01, 9.94045404e-04,
        1.38083578e-05],
       [9.14122105e-01, 8.58771801e-02, 4.07705102e-07, 5.91389160e-09,
        2.21042285e-07],
       [2.49272744e-05, 5.31641424e-01, 4.68317658e-01, 1.52225739e-05,
        9.14287682e-07],
       [6.24290705e-01, 3.75707984e-01, 1.10969108e-06, 7.44967998e-09,
        2.03797583e-07],
       [1.07662245e-05, 9.99374330e-01, 6.14950492e-04, 1.57758304e-08,
        5.38658318e-09],
       [6.32473821e-05, 9.62664366e-01, 3.72676179e-02, 4.05221408e-06,
        6.83124767e-07],
       [8.47420324e-06, 9.61870432e-01, 3.81204672e-02, 5.37057645e-07,
        2.97297529e-08],
       [1.89110850e-07, 3.11060503e-05, 9.46295142e-01, 5.36623448e-02,
        1.11656318e-05],
       [2.27207041e-04, 9.99772549e-01, 2.99775280e-07, 1.73775942e-11,
        1.34026817e-10],
       [1.48628210e-03, 9.98495221e-01, 1.84048040e-05, 8.49706705e-09,
        4.09452028e-08],
       [2.51869547e-09, 9.23323551e-09, 5.53175865e-04, 9.99196827e-01,
        2.50034791e-04],
       [2.96971177e-08, 5.77154336e-04, 9.99279737e-01, 1.42936260e-04,
        8.18435666e-08],
       [1.80442086e-07, 6.84627230e-05, 9.88308907e-01, 1.16106914e-02,
        1.16583406e-05],
       [7.58542796e-04, 9.99236584e-01, 4.90284265e-06, 1.28468491e-09,
        6.55648957e-09],
       [8.08371187e-05, 9.96045709e-01, 3.87302623e-03, 2.62845447e-07,
        1.32477439e-07],
       [9.18185528e-09, 3.73749316e-07, 1.17810667e-01, 8.82121801e-01,
        6.70386216e-05],
       [4.93820953e-05, 9.99947011e-01, 3.57123099e-06, 3.47593516e-11,
        1.80270424e-10],
       [5.31051150e-08, 4.57222086e-05, 9.95485187e-01, 4.46684845e-03,
        2.00936483e-06],
       [2.90619522e-01, 7.09367514e-01, 1.16258934e-05, 1.11821016e-07,
        1.23797065e-06],
       [1.40262544e-02, 9.85971928e-01, 1.77283925e-06, 1.64523051e-09,
        1.36275107e-08],
       [9.96178627e-01, 3.82139301e-03, 1.64737494e-11, 6.10168451e-14,
        1.89790093e-11],
       [2.68170275e-02, 9.73181546e-01, 1.39625195e-06, 1.67992842e-09,
        2.06352038e-08],
       [6.56763268e-06, 8.23849812e-03, 9.90793049e-01, 9.51797760e-04,
        1.01730511e-05],
       [1.01481915e-01, 8.98508191e-01, 9.73995338e-06, 1.47963286e-08,
        1.69306247e-07],
       [2.76267656e-07, 4.22423780e-01, 5.77575386e-01, 5.27458894e-07,
        7.99281796e-09],
       [2.27320402e-06, 5.30555919e-02, 9.46907997e-01, 3.35835903e-05,
        4.35990046e-07],
       [1.16740512e-06, 9.99958456e-01, 4.02834339e-05, 1.31045383e-10,
        5.19078773e-11],
       [2.53885781e-04, 9.99310195e-01, 4.35706752e-04, 1.34201599e-07,
        9.74277157e-08],
       [4.05754618e-05, 9.99943316e-01, 1.60629024e-05, 8.40239212e-10,
        1.40251644e-09],
       [2.97676797e-06, 4.32774075e-04, 9.48891461e-01, 5.04599288e-02,
        2.13025458e-04],
       [4.66549955e-06, 2.84059644e-01, 7.15911746e-01, 2.36242759e-05,
        2.25525469e-07],
       [9.99941409e-01, 5.85253110e-05, 7.07012953e-13, 1.64365202e-14,
        5.72880198e-12],
       [4.54620505e-07, 6.31274132e-04, 9.98183787e-01, 1.18230388e-03,
        2.20034235e-06],
       [9.99221504e-01, 7.78540678e-04, 1.67161701e-11, 2.83546569e-13,
        6.14358356e-11],
       [3.00902780e-03, 9.96757746e-01, 2.32082413e-04, 3.55028504e-07,
        8.41339101e-07],
       [3.54691874e-04, 9.99439836e-01, 2.05104763e-04, 6.32551433e-08,
        9.18023417e-08],
       [5.43621582e-06, 9.99033034e-01, 9.61459940e-04, 8.87352325e-09,
        2.68227307e-09],
       [6.58237636e-02, 9.34170008e-01, 6.03659009e-06, 1.24402062e-08,
        1.97785909e-07],
       [8.78041267e-01, 1.21952496e-01, 3.75141212e-06, 1.17938605e-07,
        2.25658482e-06],
       [9.18672161e-09, 2.82286404e-04, 9.99616563e-01, 1.01165533e-04,
        2.33411548e-08],
       [4.62253920e-05, 9.99060094e-01, 8.93687014e-04, 4.91530372e-08,
        2.29366339e-08],
       [3.33034382e-06, 9.99996483e-01, 1.13609879e-07, 2.43267076e-13,
        5.92744820e-13],
       [1.50269235e-03, 9.98488545e-01, 8.55457347e-06, 3.63307096e-09,
        1.67431065e-08],
       [4.89489196e-07, 1.37300026e-02, 9.86174583e-01, 9.47482549e-05,
        2.60397996e-07],
       [1.62646873e-04, 9.66034114e-01, 3.37947831e-02, 7.25683049e-06,
        1.18305536e-06],
       [8.20711830e-06, 3.82817656e-01, 6.17135644e-01, 3.77244542e-05,
        7.25979135e-07],
       [1.67506470e-04, 9.99788284e-01, 4.43618228e-05, 4.16410550e-09,
        9.33107280e-09],
       [9.99775887e-01, 2.24190968e-04, 1.23893439e-11, 4.72744456e-13,
        8.56281990e-11],
       [2.72650039e-03, 9.97270107e-01, 3.47225659e-06, 1.83137849e-09,
        1.47247556e-08],
       [7.26640574e-05, 9.99926865e-01, 3.41541750e-07, 5.56236480e-12,
        3.37436468e-11],
       [1.02654937e-07, 3.03107500e-03, 9.96895552e-01, 7.30505344e-05,
        9.52221271e-08],
       [1.11735255e-06, 9.99928772e-01, 7.01060926e-05, 2.81563189e-10,
        1.03549114e-10],
       [7.75018513e-01, 2.24974602e-01, 5.20926278e-06, 6.84217838e-08,
        1.69026316e-06],
       [6.06277940e-13, 1.18277220e-12, 3.09579627e-06, 9.99890745e-01,
        1.06039734e-04],
       [3.91747790e-07, 8.48269742e-03, 9.91465807e-01, 5.09410711e-05,
        1.70517168e-07],
       [3.50057053e-05, 9.99092340e-01, 8.72603850e-04, 3.58231098e-08,
        1.50051029e-08],
       [1.46740314e-03, 9.98510003e-01, 2.24703399e-05, 1.33868934e-08,
        5.20774321e-08],
       [3.92751121e-09, 1.25610846e-08, 1.23548519e-03, 9.90088224e-01,
        8.67616013e-03],
       [1.27770181e-04, 9.98684168e-01, 1.18761067e-03, 1.94613335e-07,
        1.43820159e-07],
       [3.70266568e-03, 9.96292531e-01, 4.74187573e-06, 4.90504259e-09,
        1.91789997e-08],
       [3.01709861e-06, 2.39197966e-02, 9.75949585e-01, 1.27120278e-04,
        4.88222611e-07],
       [8.37051539e-06, 9.97433841e-01, 2.55781855e-03, 5.81710466e-08,
        1.35498004e-08],
       [4.89777594e-04, 9.90128338e-01, 9.37242806e-03, 5.26978420e-06,
        4.12356349e-06],
       [5.82901885e-06, 3.49271670e-03, 9.95365381e-01, 1.12253812e-03,
        1.35727805e-05],
       [3.22815572e-06, 9.72366154e-01, 2.76304930e-02, 1.41548114e-07,
        1.02356950e-08],
       [1.61839896e-04, 2.29511000e-02, 9.69471574e-01, 7.07715983e-03,
        3.38329119e-04],
       [9.64434310e-09, 1.44224014e-05, 9.93150949e-01, 6.83424156e-03,
        2.68337573e-07],
       [2.53240051e-09, 3.14435529e-05, 9.99235153e-01, 7.33357912e-04,
        3.47858418e-08],
       [8.06509793e-01, 1.93490177e-01, 1.19667973e-08, 1.64038262e-11,
        1.49706925e-09],
       [2.71012308e-03, 9.97113764e-01, 1.75045978e-04, 2.39719554e-07,
        7.19328455e-07],
       [8.47255777e-08, 5.36107336e-06, 3.97468746e-01, 6.02459729e-01,
        6.60981241e-05],
       [2.39722256e-04, 9.95803535e-01, 3.95458611e-03, 1.53000985e-06,
        7.26788926e-07],
       [1.78785383e-04, 4.26072240e-01, 5.73268116e-01, 4.55965550e-04,
        2.49229524e-05],
       [4.74232684e-06, 4.05398384e-02, 9.59313571e-01, 1.39979195e-04,
        1.89515606e-06],
       [5.16080254e-05, 3.51742767e-02, 9.63199973e-01, 1.53807097e-03,
        3.60985759e-05],
       [2.94067082e-03, 9.97053862e-01, 5.51164158e-06, 3.12241411e-09,
        1.85919191e-08],
       [5.66592276e-01, 4.33402359e-01, 4.88531987e-06, 2.54858161e-08,
        4.56106136e-07],
       [9.59205151e-01, 4.07948196e-02, 4.67574557e-09, 2.70981449e-11,
        1.49189194e-09],
       [7.35931394e-07, 9.69534218e-01, 3.04650515e-02, 6.23447676e-08,
        1.68168957e-09],
       [1.60771506e-05, 4.88126487e-01, 5.11834979e-01, 2.16757817e-05,
        7.93030438e-07],
       [8.14468513e-05, 9.99565065e-01, 3.53445852e-04, 3.33807542e-08,
        2.52444465e-08],
       [3.09780205e-07, 1.47825158e-05, 4.21487987e-01, 5.75816870e-01,
        2.68012076e-03],
       [2.83842546e-05, 2.55782545e-01, 7.44073033e-01, 1.11159599e-04,
        4.88646219e-06],
       [7.49590035e-05, 9.99787569e-01, 1.37383497e-04, 1.11844507e-08,
        1.00013064e-08],
       [1.08299134e-02, 9.89092469e-01, 7.66808298e-05, 1.34272710e-07,
        8.63853359e-07],
       [1.11498474e-03, 9.98276711e-01, 6.07283320e-04, 4.93659854e-07,
        5.62042715e-07],
       [4.08721633e-07, 9.95657146e-01, 4.34242981e-03, 5.83711079e-09,
        6.00386407e-10],
       [2.73101193e-07, 3.52510880e-03, 9.96295989e-01, 1.78283008e-04,
        4.00278225e-07],
       [6.15126500e-03, 9.93784547e-01, 6.37089906e-05, 9.64448361e-08,
        3.65730585e-07],
       [9.27032888e-01, 7.29669705e-02, 1.14461201e-07, 1.06691400e-09,
        4.72675481e-08],
       [1.43683091e-01, 8.54793668e-01, 1.32888695e-03, 3.79086669e-05,
        1.56396010e-04],
       [5.28003881e-08, 4.04023769e-04, 9.99446034e-01, 1.49699874e-04,
        1.49373506e-07],
       [2.87565775e-03, 9.97099757e-01, 2.45331648e-05, 1.54790634e-08,
        8.46064765e-08],
       [2.11623893e-03, 9.97740030e-01, 1.43124518e-04, 1.75495245e-07,
        4.20103618e-07],
       [1.32887328e-06, 5.74846007e-03, 9.94093537e-01, 1.55522765e-04,
        1.20888251e-06],
       [2.50689354e-05, 6.37037814e-01, 3.62916619e-01, 1.96690471e-05,
        8.50836841e-07],
       [3.52424945e-06, 9.75331068e-01, 2.46652048e-02, 2.02352354e-07,
        1.87660323e-08],
       [8.30755234e-01, 1.69241473e-01, 2.09056452e-06, 4.92704153e-08,
        1.14223167e-06],
       [1.38543737e-05, 8.76241624e-01, 1.23739801e-01, 4.47401044e-06,
        2.50897557e-07],
       [7.57653197e-07, 1.29806849e-05, 9.01372582e-02, 9.09333169e-01,
        5.15870634e-04],
       [1.63739855e-09, 2.67593748e-07, 2.13229120e-01, 7.86766648e-01,
        4.06768459e-06],
       [5.86874557e-06, 1.09325501e-03, 9.90734518e-01, 8.12908728e-03,
        3.74568626e-05],
       [9.98491406e-01, 1.50844641e-03, 2.00901545e-10, 4.29379492e-12,
        4.93322383e-10],
       [4.65110861e-06, 9.91792381e-01, 8.20288993e-03, 1.29509189e-07,
        1.37383989e-08],
       [7.07012805e-06, 2.12485008e-02, 9.78472769e-01, 2.64649076e-04,
        6.89659464e-06],
       [1.07230278e-06, 9.88585949e-01, 1.14130648e-02, 2.77281096e-08,
        1.65182779e-09],
       [1.01148556e-08, 3.19073870e-08, 1.27509178e-03, 9.94796097e-01,
        3.92869581e-03],
       [3.42987114e-05, 2.72495180e-01, 7.27356136e-01, 1.07986169e-04,
        6.37530820e-06],
       [5.51937603e-07, 2.15713475e-02, 9.78363276e-01, 6.47720808e-05,
        1.30195360e-07],
       [9.89388525e-01, 1.06114559e-02, 2.77874310e-08, 9.71236314e-10,
        3.84712315e-08],
       [8.49150019e-05, 9.99648690e-01, 2.66378542e-04, 3.28687406e-08,
        2.04612043e-08],
       [5.64530910e-06, 9.99912918e-01, 8.13861989e-05, 2.69943207e-10,
        2.91911606e-10],
       [3.26143466e-02, 9.67330933e-01, 5.23955678e-05, 1.77116647e-07,
        2.02177625e-06],
       [4.31959081e-04, 9.99149978e-01, 4.17720294e-04, 9.08195403e-08,
        1.44279412e-07],
       [2.16783228e-04, 9.99712467e-01, 7.08032676e-05, 1.59768501e-08,
        2.48776981e-08],
       [1.14127285e-08, 4.48595802e-06, 9.40036356e-01, 5.99579848e-02,
        1.24306507e-06],
       [1.41402334e-10, 2.36804465e-09, 2.91014207e-03, 9.97014642e-01,
        7.52692285e-05],
       [1.89314336e-01, 8.10685217e-01, 3.87310820e-07, 4.03142408e-10,
        1.82633890e-08],
       [4.82473150e-03, 9.94946361e-01, 2.27412966e-04, 4.18101109e-07,
        1.10968756e-06],
       [6.77808560e-03, 9.93218124e-01, 3.75976083e-06, 1.96788585e-09,
        1.76953545e-08],
       [4.05170613e-06, 3.41427296e-01, 6.58565342e-01, 3.16562046e-06,
        1.35008037e-07],
       [1.22796814e-03, 9.98572469e-01, 1.99177433e-04, 1.31168321e-07,
        2.81391209e-07],
       [7.73495117e-07, 2.18265923e-03, 9.97346818e-01, 4.69142309e-04,
        5.55311942e-07],
       [1.10866345e-07, 2.02015825e-02, 9.79788721e-01, 9.63272305e-06,
        3.63425094e-08],
       [9.87023771e-01, 1.29763288e-02, 2.68433897e-08, 8.06596401e-10,
        3.80226943e-08],
       [1.79081544e-04, 9.99527991e-01, 2.92717101e-04, 5.32096323e-08,
        6.92605298e-08],
       [1.26651412e-06, 3.32394011e-05, 2.78716505e-01, 7.17973173e-01,
        3.27582634e-03],
       [1.58784985e-09, 2.16602657e-05, 9.99403358e-01, 5.74922189e-04,
        2.53546713e-08],
       [5.87882474e-04, 9.99403596e-01, 8.41230212e-06, 2.55997223e-09,
        9.50778745e-09],
       [1.60214108e-06, 3.42578053e-01, 6.57414615e-01, 5.68398991e-06,
        7.25886906e-08],
       [1.06676774e-08, 1.39259815e-03, 9.98602152e-01, 5.24764209e-06,
        4.45317161e-09],
       [5.74096339e-06, 2.17878535e-01, 7.82074869e-01, 4.01784419e-05,
        7.31829005e-07],
       [1.24091050e-03, 9.98588920e-01, 1.69713632e-04, 7.15607342e-08,
        2.76168777e-07],
       [2.69269824e-01, 7.30729640e-01, 5.17556884e-07, 1.58491664e-09,
        3.94600121e-08],
       [2.27311830e-05, 9.97131228e-01, 2.84593808e-03, 9.50767429e-08,
        3.54721301e-08],
       [2.05172964e-05, 4.94453404e-03, 9.90066171e-01, 4.88264300e-03,
        8.60268046e-05],
       [1.47051804e-04, 8.33342433e-01, 1.66480601e-01, 2.31224622e-05,
        6.80859921e-06],
       [5.68866085e-07, 9.97755408e-01, 2.24391581e-03, 3.19511773e-09,
        4.10367434e-10],
       [1.55346029e-07, 7.20486715e-02, 9.27947700e-01, 3.46510797e-06,
        1.65895315e-08],
       [3.66324890e-08, 1.79957831e-03, 9.98185217e-01, 1.50710157e-05,
        1.25886714e-08],
       [8.23794267e-07, 9.97095585e-01, 2.90354341e-03, 2.23313212e-09,
        4.30236291e-10],
       [4.06244317e-06, 7.15793788e-01, 2.84198314e-01, 3.59813680e-06,
        1.11599576e-07],
       [1.30917749e-06, 9.91975237e-03, 9.89968896e-01, 1.09150060e-04,
        8.51767936e-07],
       [6.95683775e-06, 9.98610795e-01, 1.38219655e-03, 2.97982261e-08,
        5.29223287e-09],
       [1.79495942e-06, 3.85422982e-06, 1.08592110e-02, 3.64113539e-01,
        6.25021577e-01],
       [9.99537051e-01, 4.62972384e-04, 2.46834497e-11, 4.82003001e-13,
        8.89796084e-11],
       [4.89260003e-07, 3.16998847e-02, 9.68276978e-01, 2.25225922e-05,
        1.63286586e-07],
       [2.14762764e-07, 2.86320108e-03, 9.96934175e-01, 2.02191193e-04,
        2.09557427e-07],
       [8.49810967e-05, 9.46733475e-01, 5.31774797e-02, 2.81217103e-06,
        1.20434538e-06],
       [4.77112678e-08, 9.86852884e-01, 1.31470999e-02, 2.42812970e-09,
        6.28874314e-11],
       [7.86547361e-08, 7.01500903e-05, 9.95556414e-01, 4.37139254e-03,
        1.78475773e-06],
       [1.31624029e-05, 7.43102014e-01, 2.56867737e-01, 1.67212365e-05,
        3.29411563e-07],
       [1.44853544e-07, 2.58596934e-04, 9.98225451e-01, 1.51507487e-03,
        6.84269310e-07],
       [9.47942226e-06, 9.97489214e-01, 2.50102766e-03, 6.22358414e-08,
        1.35944056e-08],
       [1.76803842e-05, 1.44512162e-01, 8.55385602e-01, 8.16370230e-05,
        2.90586354e-06],
       [9.55903215e-06, 3.04358184e-01, 6.95562184e-01, 6.94924311e-05,
        5.80746644e-07],
       [3.81060634e-12, 3.28944094e-10, 1.71893067e-03, 9.98280287e-01,
        7.74980720e-07],
       [1.92866949e-08, 4.40707527e-06, 6.83114290e-01, 3.16866457e-01,
        1.47149713e-05],
       [3.70419502e-06, 2.23779120e-03, 9.97117221e-01, 6.29519811e-04,
        1.17504960e-05],
       [2.73402984e-04, 9.99624670e-01, 1.01963400e-04, 1.55558073e-08,
        3.34419497e-08],
       [8.33596857e-07, 2.66975135e-01, 7.33020604e-01, 3.42664043e-06,
        2.96586062e-08],
       [2.37576558e-07, 3.71134483e-05, 9.65785325e-01, 3.41521055e-02,
        2.53783455e-05],
       [6.37249832e-06, 4.94462656e-05, 1.29390106e-01, 8.53026271e-01,
        1.75278839e-02],
       [1.53186505e-07, 9.97193158e-01, 2.80661508e-03, 1.57938407e-09,
        8.12956577e-11],
       [1.73590786e-09, 1.14744893e-04, 9.99838352e-01, 4.68567414e-05,
        2.85914736e-09],
       [4.32671309e-01, 5.67325652e-01, 2.64365713e-06, 1.91213800e-08,
        3.14769949e-07],
       [1.82216372e-05, 2.33503923e-01, 7.66440094e-01, 3.57585996e-05,
        1.98401835e-06],
       [1.19217566e-05, 5.19229583e-02, 9.47921395e-01, 1.34621732e-04,
        9.25123732e-06],
       [6.16391897e-01, 3.83607805e-01, 3.28530120e-07, 1.87706162e-09,
        5.15099359e-08],
       [6.09521294e-07, 2.53363280e-03, 9.97057199e-01, 4.07373067e-04,
        1.10474616e-06],
       [6.98794305e-01, 3.01204771e-01, 7.15156204e-07, 5.31324673e-09,
        1.34031751e-07],
       [4.68646233e-09, 1.58214592e-04, 9.99752998e-01, 8.88001232e-05,
        2.89435942e-08],
       [3.02769709e-03, 9.96908665e-01, 6.32328665e-05, 8.87518539e-08,
        3.07959624e-07],
       [8.41379285e-01, 1.58618361e-01, 1.80114955e-06, 2.86398780e-08,
        5.38329118e-07],
       [3.26011588e-07, 7.94833031e-05, 9.66218829e-01, 3.36907394e-02,
        1.05625395e-05],
       [1.73966604e-04, 9.99818325e-01, 7.78695903e-06, 9.63942703e-10,
        3.18087001e-09],
       [4.65452584e-04, 9.99532163e-01, 2.40514305e-06, 3.35583616e-10,
        1.43953383e-09],
       [2.27868702e-09, 5.80498849e-08, 1.54637629e-02, 9.84465837e-01,
        7.02700927e-05],
       [1.63981753e-07, 1.39451498e-04, 9.96923983e-01, 2.93274457e-03,
        3.52245615e-06],
       [5.59850619e-08, 2.27486979e-07, 5.72561519e-03, 9.86748815e-01,
        7.52541097e-03],
       [8.76921058e-01, 1.23078994e-01, 3.46483766e-08, 2.20625074e-10,
        1.14418288e-08],
       [1.86356119e-04, 9.81523156e-01, 1.82856135e-02, 3.24170378e-06,
        1.61309765e-06],
       [2.19628360e-04, 1.01734079e-01, 8.96487236e-01, 1.45442085e-03,
        1.04656945e-04],
       [1.25671068e-04, 2.82718986e-02, 9.69997287e-01, 1.30214763e-03,
        3.03066190e-04]], dtype=float32)

In [ ]:
from sklearn.metrics import classification_report
import numpy as np
y_pred_labels = np.argmax(y_pred, axis=1)
rep=classification_report(y_test,y_pred_labels)
print(rep)

              precision    recall  f1-score   support

         0.0       0.73      0.84      0.78        19
         1.0       0.94      0.90      0.92        92
         2.0       0.95      0.92      0.93        76
         3.0       0.67      0.83      0.74        12
         4.0       0.00      0.00      0.00         1

    accuracy                           0.90       200
   macro avg       0.66      0.70      0.68       200
weighted avg       0.90      0.90      0.90       200

# UI Design Colab in VS Code

In [ ]:
model.save("student_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
import joblib

joblib.dump(scaler, "scaler.pkl")
joblib.dump(oe, "ordinal_encoder.pkl")
joblib.dump(le, "label_encoder.pkl")

['label_encoder.pkl']